{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "execution": {
     "iopub.execute_input": "2023-07-29T22:49:10.097087Z",
     "iopub.status.busy": "2023-07-29T22:49:10.096334Z",
     "iopub.status.idle": "2023-07-29T22:49:12.582369Z",
     "shell.execute_reply": "2023-07-29T22:49:12.581770Z",
     "shell.execute_reply.started": "2023-07-29T22:49:10.097064Z"
    },
    "id": "n337KoD2om3L",
    "outputId": "97ada0c6-f21c-483e-d63d-08abddd49004"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Mon Jul 31 00:24:02 2023       \n",
      "+---------------------------------------------------------------------------------------+\n",
      "| NVIDIA-SMI 536.67                 Driver Version: 536.67       CUDA Version: 12.2     |\n",
      "|-----------------------------------------+----------------------+----------------------+\n",
      "| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |\n",
      "| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |\n",
      "|                                         |                      |               MIG M. |\n",
      "|=========================================+======================+======================|\n",
      "|   0  NVIDIA GeForce RTX 4070 Ti   WDDM  | 00000000:2D:00.0  On |                  N/A |\n",
      "|  0%   37C    P8               7W / 285W |   2607MiB / 12282MiB |      2%      Default |\n",
      "|                                         |                      |                  N/A |\n",
      "+-----------------------------------------+----------------------+----------------------+\n",
      "                                                                                         \n",
      "+---------------------------------------------------------------------------------------+\n",
      "| Processes:                                                                            |\n",
      "|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |\n",
      "|        ID   ID                                                             Usage      |\n",
      "|=======================================================================================|\n",
      "|    0   N/A  N/A      8104    C+G   ...tionsPlus\\logioptionsplus_agent.exe    N/A      |\n",
      "|    0   N/A  N/A      9156    C+G   C:\\Windows\\explorer.exe                   N/A      |\n",
      "|    0   N/A  N/A     11288    C+G   ...nt.CBS_cw5n1h2txyewy\\SearchHost.exe    N/A      |\n",
      "|    0   N/A  N/A     11312    C+G   ...2txyewy\\StartMenuExperienceHost.exe    N/A      |\n",
      "|    0   N/A  N/A     12040    C+G   ...5n1h2txyewy\\ShellExperienceHost.exe    N/A      |\n",
      "|    0   N/A  N/A     12740    C+G   ...siveControlPanel\\SystemSettings.exe    N/A      |\n",
      "|    0   N/A  N/A     13164    C+G   ...64__8wekyb3d8bbwe\\CalculatorApp.exe    N/A      |\n",
      "|    0   N/A  N/A     14392    C+G   ...crosoft\\Edge\\Application\\msedge.exe    N/A      |\n",
      "|    0   N/A  N/A     15688    C+G   ...47.0_x64__zpdnekdrzrea0\\Spotify.exe    N/A      |\n",
      "|    0   N/A  N/A     19172    C+G   ...ekyb3d8bbwe\\PhoneExperienceHost.exe    N/A      |\n",
      "|    0   N/A  N/A     21260    C+G   ...t.LockApp_cw5n1h2txyewy\\LockApp.exe    N/A      |\n",
      "|    0   N/A  N/A     21588    C+G   ...GeForce Experience\\NVIDIA Share.exe    N/A      |\n",
      "|    0   N/A  N/A     21748    C+G   ...GeForce Experience\\NVIDIA Share.exe    N/A      |\n",
      "|    0   N/A  N/A     23320    C+G   ...n\\115.0.1901.188\\msedgewebview2.exe    N/A      |\n",
      "|    0   N/A  N/A     23484    C+G   ...cal\\Microsoft\\OneDrive\\OneDrive.exe    N/A      |\n",
      "|    0   N/A  N/A     23724    C+G   ...\\cef\\cef.win7x64\\steamwebhelper.exe    N/A      |\n",
      "|    0   N/A  N/A     24744    C+G   ...n\\115.0.1901.188\\msedgewebview2.exe    N/A      |\n",
      "|    0   N/A  N/A     26892    C+G   ...ocal\\Programs\\nordpass\\NordPass.exe    N/A      |\n",
      "|    0   N/A  N/A     28504    C+G   ...al\\Discord\\app-1.0.9015\\Discord.exe    N/A      |\n",
      "|    0   N/A  N/A     28584    C+G   ...es\\Docker\\Docker\\Docker Desktop.exe    N/A      |\n",
      "|    0   N/A  N/A     30060    C+G   ...\\Docker\\frontend\\Docker Desktop.exe    N/A      |\n",
      "|    0   N/A  N/A     32484    C+G   ...CBS_cw5n1h2txyewy\\TextInputHost.exe    N/A      |\n",
      "|    0   N/A  N/A     34144    C+G   ...r+1689928519420\\Code - Insiders.exe    N/A      |\n",
      "+---------------------------------------------------------------------------------------+\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\tqdm\\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n",
      "2023-07-31 00:24:04 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX\n",
      "c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\torchaudio\\backend\\utils.py:74: UserWarning: No audio backend is available.\n",
      "  warnings.warn(\"No audio backend is available.\")\n",
      "2023-07-31 00:24:05,658\tINFO util.py:159 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.\n"
     ]
    }
   ],
   "source": [
    "!nvidia-smi\n",
    "\n",
    "# imports\n",
    "import math\n",
    "import wave\n",
    "import struct\n",
    "import os\n",
    "import urllib.request\n",
    "import tarfile\n",
    "import random\n",
    "from audiolm_pytorch import SoundStream, SoundStreamTrainer, HubertWithKmeans, SemanticTransformer, SemanticTransformerTrainer, HubertWithKmeans, CoarseTransformer, CoarseTransformerWrapper, CoarseTransformerTrainer, FineTransformer, FineTransformerWrapper, FineTransformerTrainer, AudioLM\n",
    "from torch import nn\n",
    "import torch\n",
    "import torchaudio\n",
    "import ray\n",
    "from random import shuffle\n",
    "from fs.osfs import OSFS\n",
    "from fs.mountfs import MountFS\n",
    "from fs import open_fs\n",
    "\n",
    "sample_rate = 16000\n",
    "\n",
    "# define all dataset paths, checkpoints, etc\n",
    "dataset_folder = \"placeholder_dataset\"\n",
    "soundstream_ckpt = \"results/soundstream.8.pt\" # this can change depending on number of steps\n",
    "hubert_ckpt = 'hubert/hubert_base_ls960.pt'\n",
    "hubert_quantizer = f'hubert/hubert_base_ls960_L9_km500.bin' # listed in row \"HuBERT Base (~95M params)\", column Quantizer"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "execution": {
     "iopub.execute_input": "2023-07-29T22:49:12.584473Z",
     "iopub.status.busy": "2023-07-29T22:49:12.583653Z",
     "iopub.status.idle": "2023-07-29T22:49:12.792203Z",
     "shell.execute_reply": "2023-07-29T22:49:12.791517Z",
     "shell.execute_reply.started": "2023-07-29T22:49:12.584449Z"
    }
   },
   "outputs": [],
   "source": [
    "import math\n",
    "from IPython.display import Audio\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "def plot_waveform(waveform, sample_rate, title=\"Waveform\", xlim=None):\n",
    "    waveform = waveform.numpy()\n",
    "\n",
    "    num_channels, num_frames = waveform.shape\n",
    "    time_axis = torch.arange(0, num_frames) / sample_rate\n",
    "\n",
    "    figure, axes = plt.subplots(num_channels, 1)\n",
    "    if num_channels == 1:\n",
    "        axes = [axes]\n",
    "    for c in range(num_channels):\n",
    "        axes[c].plot(time_axis, waveform[c], linewidth=1)\n",
    "        axes[c].grid(True)\n",
    "        if num_channels > 1:\n",
    "            axes[c].set_ylabel(f\"Channel {c+1}\")\n",
    "        if xlim:\n",
    "            axes[c].set_xlim(xlim)\n",
    "    figure.suptitle(title)\n",
    "    plt.show(block=False)\n",
    "    \n",
    "def plot_specgram(waveform, sample_rate, title=\"Spectrogram\", xlim=None):\n",
    "    waveform = waveform.numpy()\n",
    "\n",
    "    num_channels, _ = waveform.shape\n",
    "\n",
    "    figure, axes = plt.subplots(num_channels, 1)\n",
    "    if num_channels == 1:\n",
    "        axes = [axes]\n",
    "    for c in range(num_channels):\n",
    "        axes[c].specgram(waveform[c], Fs=sample_rate)\n",
    "        if num_channels > 1:\n",
    "            axes[c].set_ylabel(f\"Channel {c+1}\")\n",
    "        if xlim:\n",
    "            axes[c].set_xlim(xlim)\n",
    "    figure.suptitle(title)\n",
    "    plt.show(block=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "execution": {
     "iopub.execute_input": "2023-07-29T22:49:12.793646Z",
     "iopub.status.busy": "2023-07-29T22:49:12.793072Z",
     "iopub.status.idle": "2023-07-29T22:49:52.955981Z",
     "shell.execute_reply": "2023-07-29T22:49:52.955233Z",
     "shell.execute_reply.started": "2023-07-29T22:49:12.793626Z"
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-07-31 00:24:08,731\tINFO worker.py:1621 -- Started a local Ray instance.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['/Psychostream-02/f9aeacced9e40a71a7f01b9731c9d302.train.5.mp3', '/Jamendo-02/136a200cbf88932feed2ef3d8d25e102.train.4.mp3', '/Psychostream-01/153b89d76fe7b3ede26e625423217e01.train.6.mp3', '/Psychostream-00/a3a9a6783941229bd8fb96a996729300.train.3.mp3', '/Psychostream-01/6677c1c8c25251a82cde5f8cd66a6601.train.3.mp3', '/Psychostream-03/c39479df8287488fbf96a6a9d7ae4803.train.5.mp3', '/Psychostream-00/869b6b5a52c765445379c44867e76c00.train.7.mp3', '/Jamendo-00/ec5226131f0010e9352768a4d16d3500.train.1.mp3', '/Psychostream-02/54c2d39073f22bc307255fd4cec35302.train.9.mp3', '/Jamendo-01/59247d8f9bc3cca2c8b002445ea28801.train.4.mp3', '/Psychostream-00/1c7a39fd89dd74f7c5f8128de4104b00.train.9.mp3', '/Psychostream-03/1b3855e83c703767d638da1d6ad87903.train.4.mp3', '/Psychostream-01/194f483d30c0032027ee55d5d1905101.train.3.mp3', '/dns4-read/chetvero_nischih_s000471_seg_0.mp3', '/Jamendo-01/0f6be55f84c3beaa755153b77a58a201.train.4.mp3', '/Psychostream-03/e79b314817ffa883d446628b520c8a03.train.4.mp3', '/Jamendo-01/a9d0166bcecd2f8de8e56cee3e544301.train.4.mp3', '/Jamendo-01/a856af9c9ce520aabab36f0fc421a801.train.1.mp3', '/Jamendo-03/4b68e5aee3feb5a6e94a09b372df0003.train.4.mp3', '/dns4-read/chetvero_nischih_s000823_seg_0.mp3', '/Psychostream-01/c93438db777a57d66bc8a3c1cb8cd301.train.5.mp3', '/Psychostream-01/d814cd32775ac6e68de4535d6b5f8701.train.8.mp3', '/Jamendo-03/95b531d5ec1b2c475bd45916bd6e0303.train.3.mp3', '/Psychostream-03/d03f412e63cf7fb974c48d29c8dd2003.train.3.mp3', '/Psychostream-02/ae561a946fe661d47cecf683f8967802.train.3.mp3', '/Jamendo-03/aace45c0bff95502c9999b56cf26f203.train.3.mp3', '/Psychostream-00/a32dc2793271bf753458372dfecad500.train.4.mp3', '/Jamendo-02/71a76465d9b718aa8cf39bd0aef19702.train.0.mp3', '/Psychostream-03/e1529dd42af72f3dc16f1d1648261203.train.11.mp3', '/Jamendo-03/ad9db1c236000ff10ba3a17d322b7e03.train.3.mp3', '/Psychostream-03/f722c242df337e6797953128c82fdf03.train.0.mp3', '/Psychostream-00/bd498c5e148b84041ada758cd57b1500.train.0.mp3', '/Psychostream-00/614c76f253ea618d293979c6cb025b00.train.1.mp3', '/Jamendo-00/f4205fb1322911e53848fe9645de2c00.train.5.mp3', '/Psychostream-01/44536bb07723119c07d04f9732220c01.train.1.mp3', '/Psychostream-02/22ad44238af35c392eccfe6a8098ec02.train.9.mp3', '/Psychostream-02/14afed2e744f1bc274fa2e942597d702.train.11.mp3', '/Psychostream-00/27fe437439ae772306e361d8e06d4900.train.7.mp3', '/Jamendo-00/af7473d5b159d2155e6b95b25a4bae00.train.2.mp3', '/Psychostream-03/5ff36697acf1547a22771857e8d7c303.train.7.mp3', '/Psychostream-03/ef53879c503b6b4a0714dfb0c4f2d403.train.8.mp3', '/Psychostream-00/b7292a6d1c3fef60c0c89262c0385a00.train.5.mp3', '/Psychostream-01/dd8dd08cf2ba02739c49af59c3e5c401.train.2.mp3', '/Psychostream-00/9408f8e6a9140a92b8466aee10625900.train.8.mp3', '/Jamendo-01/18763c1000f7859facac1a9614516801.train.0.mp3', '/Psychostream-02/fd542257678af180448a3f92b8206902.train.9.mp3', '/Psychostream-00/7d60cde63cd48b0627bbb5ca33db8700.train.9.mp3', '/Psychostream-00/63e35e40a07688a98e78d3ecf6ab3700.train.4.mp3', '/Jamendo-03/c31b6f207f0203d0a30bc5fd9f32c703.train.0.mp3', '/Psychostream-03/7bd922f280967c6c85b9a387afc11c03.train.11.mp3']\n"
     ]
    }
   ],
   "source": [
    "ray.init(num_cpus=16, num_gpus=1)\n",
    "\n",
    "# Setup filesystem\n",
    "dataset_fs = MountFS()\n",
    "\n",
    "#dataset_fs.mount('dns4-read', open_fs('s3://music-clip-dataset/dns/clean-fullband/read_speech/'))\n",
    "dataset_fs.mount('dns4-read', open_fs('s3://music-clip-dataset/dns/clean-fullband/russian/M-AILABS_Speech_Dataset/ru_RU_47hrs_48k/female/hajdurova/chetvero_nischih/wavs/'))\n",
    "[dataset_fs.mount(f'Jamendo-{_:02x}', open_fs(f's3://music-clip-dataset/clips/train/{_:02x}/')) for _ in range(4)]\n",
    "[dataset_fs.mount(f'Psychostream-{_:02x}', open_fs(f's3://music-clip-dataset/psychostream/train/{_:02x}/')) for _ in range(4)]\n",
    "#dataset_fs.add_fs('dns4-read', open_fs('s3://music-clip-dataset/dns/clean-fullband/read_speech/'))\n",
    "\n",
    "# Get all music files and shuffle them\n",
    "music_files = []\n",
    "for path in dataset_fs.walk.files(filter=['*.mp3']):\n",
    "    music_files.append(path)\n",
    "    #print(path)\n",
    "random.shuffle(music_files)\n",
    "print(music_files[:50])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "execution": {
     "iopub.execute_input": "2023-07-29T22:49:52.957595Z",
     "iopub.status.busy": "2023-07-29T22:49:52.957380Z",
     "iopub.status.idle": "2023-07-29T22:49:52.971373Z",
     "shell.execute_reply": "2023-07-29T22:49:52.970933Z",
     "shell.execute_reply.started": "2023-07-29T22:49:52.957561Z"
    },
    "id": "jwYCbFpHvmRI"
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=16192)\u001b[0m c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\torchaudio\\backend\\utils.py:74: UserWarning: No audio backend is available.\n",
      "\u001b[2m\u001b[36m(pid=16192)\u001b[0m   warnings.warn(\"No audio backend is available.\")\n",
      "2023-07-31 00:25:00,785\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,787\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,788\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,789\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,790\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,792\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,792\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,793\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,795\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,796\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,797\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,798\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,798\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,799\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,801\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,802\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,803\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,804\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,805\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,806\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,807\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,808\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,809\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,810\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,811\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,812\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,813\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,815\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,816\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,818\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,819\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,820\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,821\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,822\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,823\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,824\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,825\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,826\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,827\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,828\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,829\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,830\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,831\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,832\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,833\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,834\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,835\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,836\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,837\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,838\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,839\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,840\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,841\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,842\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,843\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,844\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,845\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,846\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,847\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,848\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,849\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,850\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,851\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,852\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,853\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,854\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,855\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,856\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,857\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,858\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,862\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,863\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,865\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,866\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,867\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,868\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,869\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,870\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,871\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,872\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,873\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,874\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,875\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,876\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,877\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,878\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,879\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,880\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,881\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,882\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,883\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,884\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,885\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,886\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,887\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,888\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,889\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,890\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,891\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,892\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,893\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,894\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,895\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,896\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,897\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,899\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,900\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,903\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,906\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n",
      "2023-07-31 00:25:00,908\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n",
      "    with self.fs.open(filename, 'rb') as f:\n",
      "AttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'\n"
     ]
    },
    {
     "ename": "RayTaskError(AttributeError)",
     "evalue": "\u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n    return method(__ray_actor, *args, **kwargs)\n  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n    return method(self, *_args, **_kwargs)\n  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n    with self.fs.open(filename, 'rb') as f:\nAttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mRayTaskError(AttributeError)\u001b[0m              Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[4], line 120\u001b[0m\n\u001b[0;32m    116\u001b[0m \u001b[39m#ds_v = SeabassIterableDataset(start=0, end=len(val_subset), files=val_subset, \u001b[39;00m\n\u001b[0;32m    117\u001b[0m \u001b[39m#                            fs=dataset_fs, effects=effects, clip_len=2.0, tick_char='*')\u001b[39;00m\n\u001b[0;32m    119\u001b[0m ds_t\u001b[39m.\u001b[39mrun()\n\u001b[1;32m--> 120\u001b[0m sample \u001b[39m=\u001b[39m ds_t\u001b[39m.\u001b[39;49mgetSample(\u001b[39m0\u001b[39;49m)\n\u001b[0;32m    121\u001b[0m \u001b[39m#time.sleep(3)\u001b[39;00m\n\u001b[0;32m    122\u001b[0m \u001b[39m#ds_v.run()\u001b[39;00m\n",
      "Cell \u001b[1;32mIn[4], line 83\u001b[0m, in \u001b[0;36mSeabassIterableDataset.getSample\u001b[1;34m(self, index)\u001b[0m\n\u001b[0;32m     81\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mgetSample\u001b[39m(\u001b[39mself\u001b[39m, index):\n\u001b[0;32m     82\u001b[0m     ready_refs, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mpending_samples \u001b[39m=\u001b[39m ray\u001b[39m.\u001b[39mwait(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mpending_samples, num_returns\u001b[39m=\u001b[39m\u001b[39m1\u001b[39m)\n\u001b[1;32m---> 83\u001b[0m     sample \u001b[39m=\u001b[39m ray\u001b[39m.\u001b[39;49mget(\u001b[39m*\u001b[39;49mready_refs)\n\u001b[0;32m     84\u001b[0m     ready_refs\u001b[39m.\u001b[39mappend(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mbatcher\u001b[39m.\u001b[39mgetSample\u001b[39m.\u001b[39mremote(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mfiles[index \u001b[39m+\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39msample_buffer_size]))\n\u001b[0;32m     85\u001b[0m     \u001b[39mreturn\u001b[39;00m sample\n",
      "File \u001b[1;32mc:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\auto_init_hook.py:24\u001b[0m, in \u001b[0;36mwrap_auto_init.<locals>.auto_init_wrapper\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     21\u001b[0m \u001b[39m@wraps\u001b[39m(fn)\n\u001b[0;32m     22\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mauto_init_wrapper\u001b[39m(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs):\n\u001b[0;32m     23\u001b[0m     auto_init_ray()\n\u001b[1;32m---> 24\u001b[0m     \u001b[39mreturn\u001b[39;00m fn(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n",
      "File \u001b[1;32mc:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\client_mode_hook.py:103\u001b[0m, in \u001b[0;36mclient_mode_hook.<locals>.wrapper\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m    101\u001b[0m     \u001b[39mif\u001b[39;00m func\u001b[39m.\u001b[39m\u001b[39m__name__\u001b[39m \u001b[39m!=\u001b[39m \u001b[39m\"\u001b[39m\u001b[39minit\u001b[39m\u001b[39m\"\u001b[39m \u001b[39mor\u001b[39;00m is_client_mode_enabled_by_default:\n\u001b[0;32m    102\u001b[0m         \u001b[39mreturn\u001b[39;00m \u001b[39mgetattr\u001b[39m(ray, func\u001b[39m.\u001b[39m\u001b[39m__name__\u001b[39m)(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n\u001b[1;32m--> 103\u001b[0m \u001b[39mreturn\u001b[39;00m func(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n",
      "File \u001b[1;32mc:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\worker.py:2493\u001b[0m, in \u001b[0;36mget\u001b[1;34m(object_refs, timeout)\u001b[0m\n\u001b[0;32m   2491\u001b[0m     worker\u001b[39m.\u001b[39mcore_worker\u001b[39m.\u001b[39mdump_object_store_memory_usage()\n\u001b[0;32m   2492\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(value, RayTaskError):\n\u001b[1;32m-> 2493\u001b[0m     \u001b[39mraise\u001b[39;00m value\u001b[39m.\u001b[39mas_instanceof_cause()\n\u001b[0;32m   2494\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m   2495\u001b[0m     \u001b[39mraise\u001b[39;00m value\n",
      "\u001b[1;31mRayTaskError(AttributeError)\u001b[0m: \u001b[36mray::SeabassBatcherComputer.getSample()\u001b[39m (pid=16192, ip=127.0.0.1, actor_id=05936a2a2189d4359735504301000000, repr=<__main__.SeabassBatcherComputer object at 0x0000023D88A85460>)\n  File \"python\\ray\\_raylet.pyx\", line 1424, in ray._raylet.execute_task\n  File \"python\\ray\\_raylet.pyx\", line 1364, in ray._raylet.execute_task.function_executor\n  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\_private\\function_manager.py\", line 726, in actor_method_executor\n    return method(__ray_actor, *args, **kwargs)\n  File \"c:\\Users\\sebas\\scoop\\apps\\mambaforge\\current\\envs\\audiolm\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 464, in _resume_span\n    return method(self, *_args, **_kwargs)\n  File \"C:\\Users\\sebas\\AppData\\Local\\Temp\\ipykernel_41584\\1530361082.py\", line 22, in getSample\n    with self.fs.open(filename, 'rb') as f:\nAttributeError: 'SeabassBatcherComputer' object has no attribute 'fs'"
     ]
    }
   ],
   "source": [
    "from email.mime import audio\n",
    "from io import BytesIO\n",
    "import os\n",
    "import random\n",
    "import itertools\n",
    "from time import time\n",
    "from einops import rearrange\n",
    "import fs.info\n",
    "from torchaudio.functional import resample\n",
    "from torch import Tensor\n",
    "import torch.nn.functional as F\n",
    "from audiolm_pytorch.soundstream import cast_tuple\n",
    "from audiolm_pytorch.utils import curtail_to_multiple\n",
    "\n",
    "@ray.remote\n",
    "class SeabassBatcherComputer():\n",
    "    def __init__(self, clip_len:float = 2.0, sample_rate=16000):\n",
    "        self.clip_len = clip_len\n",
    "        self.sample_rate = sample_rate\n",
    "\n",
    "    def getSample(self, filename):\n",
    "        with self.fs.open(filename, 'rb') as f:\n",
    "            reader = torchaudio.io.StreamReader(src = f)\n",
    "            reader.add_basic_audio_stream(\n",
    "                frames_per_chunk=self.sample_rate//10,\n",
    "                stream_index=0,\n",
    "                sample_rate=self.sample_rate,\n",
    "            )\n",
    "\n",
    "            audio_tensor = None\n",
    "            for i, waveform in enumerate(reader.stream()):\n",
    "                if audio_tensor is None:\n",
    "                    audio_tensor = waveform[0]\n",
    "                else:\n",
    "                    audio_tensor = torch.cat((audio_tensor, waveform[0]), 0)\n",
    "                \n",
    "                streamed_len = (audio_tensor.shape[0] / self.sample_rate) \n",
    "                if streamed_len >= self.clip_len:\n",
    "                    break # we have enough data\n",
    "\n",
    "            audio_tensor = audio_tensor.reshape(1, -1) \n",
    "            if audio_tensor.shape[0] > 1:\n",
    "                # the audio has more than 1 channel, convert to mono\n",
    "                audio_tensor = torch.mean(audio_tensor, dim=0).unsqueeze(0)\n",
    "\n",
    "            output = []\n",
    "            audio_length = audio_tensor.size(1)\n",
    "\n",
    "            ## pad or curtail\n",
    "            #max_length = 99999999999999\n",
    "            #if audio_length > max_length:\n",
    "            #    max_start = audio_length - max_length\n",
    "            #    start = torch.randint(0, max_start, (1, ))\n",
    "            #    audio_tensor = audio_tensor[:, start:start + max_length]\n",
    "            #else:\n",
    "            #    audio_tensor = F.pad(audio_tensor, (0, max_length - audio_length), 'constant')\n",
    "\n",
    "            audio_tensor = rearrange(audio_tensor, '1 ... -> ...')\n",
    "            output = audio_tensor.float()\n",
    "            return output\n",
    "\n",
    "class SeabassIterableDataset(torch.utils.data.IterableDataset):\n",
    "    def __init__(self, start, end, files: list[str], fs: MountFS, effects, clip_len:float = 2.0, tick_char='.', sample_rate=16000, sample_buffer_size=128):\n",
    "        super(SeabassIterableDataset).__init__()\n",
    "        self.start = start\n",
    "        self.end = end\n",
    "        self.effects = effects\n",
    "        self.files = files\n",
    "        self.fs = fs\n",
    "        self.clip_len = clip_len\n",
    "        self.tick_char = tick_char\n",
    "        self.sample_rate = sample_rate\n",
    "        self.sample_buffer_size = sample_buffer_size\n",
    "        self.batcher = SeabassBatcherComputer.remote(clip_len, sample_rate)\n",
    "        self.pending_samples = []\n",
    "        \n",
    "    # Start producing sasmples\n",
    "    def run(self):\n",
    "        self.pending_samples.extend(self.batcher.getSample.remote(self.files[i]) for i in range(self.sample_buffer_size))\n",
    "\n",
    "    def getSample(self, index):\n",
    "        ready_refs, self.pending_samples = ray.wait(self.pending_samples, num_returns=1)\n",
    "        sample = ray.get(*ready_refs)\n",
    "        ready_refs.append(self.batcher.getSample.remote(self.files[index + self.sample_buffer_size]))\n",
    "        return sample\n",
    "    \n",
    "    def __iter__(self):\n",
    "        worker_info = torch.utils.data.get_worker_info()\n",
    "        if worker_info is None:  # single-process data loading, return the full iterator\n",
    "            iter_start = self.start\n",
    "            iter_end = self.end\n",
    "        else:  # in a worker process\n",
    "            # split workload\n",
    "            per_worker = int(math.ceil((self.end - self.start) / float(worker_info.num_workers)))\n",
    "            worker_id = worker_info.id\n",
    "            iter_start = self.start + worker_id * per_worker\n",
    "            iter_end = min(iter_start + per_worker, self.end)\n",
    "\n",
    "        for i in range(iter_start, iter_end):\n",
    "            sample = self.getSample(i)\n",
    "            yield sample\n",
    "\n",
    "# Setup dataloader\n",
    "effects = [\n",
    "    [\"norm\", \"1\"],\n",
    "]\n",
    "\n",
    "needed_clip_len = float(320 * 40)/sample_rate\n",
    "\n",
    "train_subset = music_files[:-1000]\n",
    "val_subset = music_files[-1000:]\n",
    "\n",
    "ds_t = SeabassIterableDataset(start=0, end=len(train_subset), files=train_subset, \n",
    "                            fs=dataset_fs, effects=effects, clip_len=needed_clip_len)\n",
    "\n",
    "#ds_v = SeabassIterableDataset(start=0, end=len(val_subset), files=val_subset, \n",
    "#                            fs=dataset_fs, effects=effects, clip_len=2.0, tick_char='*')\n",
    "\n",
    "ds_t.run()\n",
    "sample = ds_t.getSample(0)\n",
    "#time.sleep(3)\n",
    "#ds_v.run()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "execution": {
     "iopub.execute_input": "2023-07-29T22:49:52.973067Z",
     "iopub.status.busy": "2023-07-29T22:49:52.972517Z",
     "iopub.status.idle": "2023-07-29T22:49:52.975350Z",
     "shell.execute_reply": "2023-07-29T22:49:52.974958Z",
     "shell.execute_reply.started": "2023-07-29T22:49:52.973047Z"
    }
   },
   "outputs": [],
   "source": [
    "# Test the sampler\n",
    "#dl_train.sampler\n",
    "#sampler = ds_train.__iter__()\n",
    "#sample = sampler.__next__()\n",
    "#print(sample)\n",
    "#print(waveform1.shape, sr1)\n",
    "#plot_waveform(waveform1, sr1, title=\"Train\", xlim=(-0.1, 3.2))\n",
    "#plot_specgram(waveform1, sr1, title=\"Train\", xlim=(0, 3.04))\n",
    "#Audio(waveform1, rate=sr1)\n",
    "#\n",
    "#_, waveform2, sr2 = ds_val.__iter__()\n",
    "#print(waveform2.shape, sr2)\n",
    "#plot_waveform(waveform2, sr2, title=\"Val\", xlim=(-0.1, 3.2))\n",
    "#plot_specgram(waveform2, sr2, title=\"Val\", xlim=(0, 3.04))\n",
    "#Audio(waveform2, rate=sr2)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "T7GiyBcBWiZV"
   },
   "source": [
    "### SoundStream"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "execution": {
     "iopub.execute_input": "2023-07-29T22:49:52.976340Z",
     "iopub.status.busy": "2023-07-29T22:49:52.975905Z"
    },
    "id": "nGU0OZiOwPEO",
    "outputId": "21dd959c-6458-4477-8403-cf810166f38d"
   },
   "outputs": [],
   "source": [
    "soundstream = SoundStream(\n",
    "    codebook_size = 1024,\n",
    "    rq_num_quantizers = 8,\n",
    ")\n",
    "\n",
    "trainer = SoundStreamTrainer(\n",
    "    soundstream,\n",
    "    #folder = dataset_folder,\n",
    "    #train_dataloader=dl_train,\n",
    "    #val_dataloader=dl_val,\n",
    "    train_dataset=dst,\n",
    "    val_dataset=dsv,\n",
    "    #lr = 0.001,\n",
    "    batch_size = 12,\n",
    "    grad_accum_every = 8,         # effective batch size of 32\n",
    "    data_max_length = 320 * 32,\n",
    "    save_results_every = 20,\n",
    "    save_model_every = 100,\n",
    "    num_train_steps = 2000,\n",
    ").cuda()\n",
    "# NOTE: I changed num_train_steps to 9 (aka 8 + 1) from 10000 to make things go faster for demo purposes\n",
    "# adjusting save_*_every variables for the same reason\n",
    "\n",
    "trainer.train()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "QoHgkgA3XKXH"
   },
   "source": [
    "## Inference"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "id": "rzghrux5WinW",
    "outputId": "9dd39f7f-0046-4a5f-826e-a442345987af"
   },
   "outputs": [],
   "source": [
    "# Everything together\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "4rQPHTSRngEr"
   },
   "outputs": [],
   "source": [
    "output_path = \"out.wav\"\n",
    "sample_rate = 44100\n",
    "torchaudio.save(output_path, generated_wav.cpu(), sample_rate)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "is9wLY_ncDYK"
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "accelerator": "GPU",
  "colab": {
   "provenance": []
  },
  "gpuClass": "standard",
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
